<div class="container">
    <div class="row">
        <?php foreach ($games as $game) : ?>
        <div class="col-12 col-sm-6 col-lg-3">
            <div class="card card-outline-primary mb-3">
                <img class="card-img-top" src="<?= DATA_WEB ?>img/game.svg" alt="Card image cap">
                <div class="card-block">
                    <h4 class="card-title"><?=$game->name ?></h4>
                    <p class="card-text">Rate: 5/5</p>
                </div>
                <div class="card-block">
                    <a href="<?=LINK_WEB ?>critic/update/<?=$game->id_games ?>" class="card-link">Update</a>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>