<div class="blog-post">
    <a class="btn btn-success" href='<?=LINK_WEB?>user/register'>Register</a>
    <!--a class="btn btn-danger" href='<?=LINK_WEB?>article/delete/<?=$article->id?>'>Delete</a-->
</div>
<div class="blog-post">
    <h2 class="blog-post-title">Login User</h2>
    <hr />
    <?php foreach ($errors as $e) : ?>
        <div class="alert alert-danger">
            <?=$e?>
        </div>
    <?php endforeach; ?>
    <form method='post'>
        <div class="form-group">
            <label for="title">Email</label>
            <input value="<?=$helpers->foundInputValue('mail')?>" type="mail" name="mail" class="form-control" id="mail"  placeholder="Enter the email">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" name='password' id="password" placeholder="Enter the password" />
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
        <a href="<?=LINK_WEB?>article" class="btn btn-secondary">Cancel</a>
    </form>
</div>